### ISSUE TITLE
Research the situation around MonoGame + .NET Core + NixOS

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Gyges#5]
1. Add nixos-unstable channel, install `dotnet-sdk`.
2. Write the following into `default.nix`:

```nix
with import <nixpkgs> {}; {
    CamanisEnv = stdenv.mkDerivation {
        rpath = stdenv.lib.makeLibraryPath [ stdenv.cc.cc libunwind libuuid icu openssl zlib curl ];
        name = "Camanis";
        buildInputs = [ mesa xorg.libX11 mono46 libunwind libuuid icu patchelf ];
        LD_LIBRARY_PATH="${libunwind}/lib:${libuuid}/lib";
    };
}
```

3. `nix-shell`
4. `dotnet run`

The output is the following:

```
Unhandled Exception: Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Failed to create graphics device! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MonoGame.OpenGL.GL.GetString(StringName name)
   at MonoGame.OpenGL.GL.LoadExtensions()
   at MonoGame.OpenGL.GL.LoadEntryPoints()
   at MonoGame.OpenGL.GraphicsContext..ctor(IWindowInfo info)
   at MonoGame.OpenGL.GL.PlatformCreateContext(IWindowInfo info)
   at MonoGame.OpenGL.GL.CreateContext(IWindowInfo info)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformSetup()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Setup()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsDeviceInformation gdi)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Camanis.Program.main(String[] argv) in /home/fornever/Camanis/Program.fs:line 11
Aborted
```

**Comment by ForNeVeR** [comment]
Voices from the other side suggested to use the following workaround:
```nix
with import <nixpkgs> {};
mkShell {
  buildInputs = [
    dotnet-sdk
    mono
  ];
  LD_LIBRARY_PATH = stdenv.lib.makeLibraryPath [
    freetype
    libGL
    pulseaudio
    xorg.libX11
    xorg.libXrandr
  ];
}
```

**Comment by PlumpMath** [comment]
Thanks ^,.^
Friedrich von Never

2019년 12월 7일 (토) 오후 10:33, Friedrich von Never <notifications@github.com>님이
작성:

**Comment by ForNeVeR** [comment]
We don't use NixOS for this game, currently. If there're any collaborators, we may resurrect the effort. Otherwise, I'm closing this for now (which doesn't mean we don't support Linux in general or NixOS for development; we do, but on the contributor-driven basis).

**Comment by libjared** [comment]
I had this problem for another MonoGame project. This happens when the OpenGL driver shared library fails to load.

For me, LD_DEBUG showed me that as it attempts to load, the version lookup for GLIBC_2.xx fails. MonoGame doesn't throw any exception at this point. `GetString` does, only because it just happens to be the first GL function call that is attempted. My NixOS system (and Mesa) was compiled with a newer glibc version than the game's ELF's interpreter. One could probably use nixGL, but updating nixpkgs to match glibc versions worked for me.

**Comment by ForNeVeR** [comment]
@libjared, thanks a lot for your help!
